version: '3.8'

services:
  # Database
  db:
    container_name: jwt-auth-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - jwt-auth-db-data:/var/lib/postgresql/data
    networks:
      - jwt-auth-network
    restart: always

volumes:
  jwt-auth-db-data:
networks:
  jwt-auth-network:
